# Get 'task' CLI from https://taskfile.dev
version: "3"

tasks:

  default:
    cmds:
      - task: all

  all:
    ignore_error: true
    desc: "Run all whoami variants"
    cmds:
      - task: aws-cli
      - task: go-whoami
      - task: node-aws-whoami-v2
      - task: node-aws-whoami-v3

  aws-cli:
    desc: "Running STS GetCallerIdentity with aws-cli"
    dir: "aws-cli"
    cmds:
      - "./whoami.sh"

  go-whoami:
    desc: "Running STS GetCallerIdentity with aws-sdk-go-v2"
    dir: "go-aws-whoami"
    cmds:
      - "go mod download"
      - "go run ."

  node-aws-whoami-v2:
    desc: "Running STS GetCallerIdentity with NPM aws-sdk v2"
    dir: "node-aws-whoami-v2"
    cmds:
      - "test -d node_modules || npm install"
      - "npm run whoami"

  node-aws-whoami-v3:
    desc: "Running STS GetCallerIdentity with NPM @aws-sdk/* v3"
    dir: "node-aws-whoami-v3"
    cmds:
      - "test -d node_modules || npm install"
      - "npm run whoami"
